#! /usr/bin/env python3

import os
import sys

from proton import Message
from proton.handlers import MessagingHandler
from proton.reactor import Container


class VZPSender(MessagingHandler):
    def __init__(self, message):
        super(VZPSender, self).__init__()
        self.message = message

    def on_start(self, event):
        event.container.create_sender("0.0.0.0:5678")

    def on_sendable(self, event):
        if os.path.exists(self.message):
            event.sender.send(Message(self.message))
            event.sender.close()
            event.connection.close()


Container(VZPSender(sys.argv[1])).run()
